// showcases/preact-showcase/src/app.jsx
import { DBButton, DBIcon } from "../../../output/preact/src";

export function App() {
  return (
    <main>
      <h1>Preact</h1>
      <div>
        <DBButton variant="primary">Test</DBButton>
        <DBButton text="Test" icon="account" />
        <DBIcon icon="account" />
      </div>
    </main>
  );
}

// showcases/vue-showcase/src/App.vue
<script setup>
import { DBButton, DBIcon } from "../../../output/vue/vue3/src";
</script>

<template>
  <main>
    <h1>Vue</h1>
    <div style="display: flex; gap: 4px; align-items: center">
      <DBButton variant="primary">Test</DBButton>
      <DBButton text="Test" icon="account" />
      <DBIcon icon="account" />
    </div>
  </main>
</template>
