// showcases/vue-showcase/src/App.vue
<script setup>
import { DBButton, DBIcon } from "../../../output/vue/vue3/src";
</script>

<template>
  <main>
    <h1>Vue</h1>
    <div style="display: flex; gap: 4px; align-items: center">
      <DBButton variant="primary">Test</DBButton>
      <DBButton text="Test" icon="account" />
      <DBIcon icon="account" />
    </div>
  </main>
</template>

// showcases/svelte-showcase/src/App.svelte
<script>
  import DBButton from "../../../output/svelte/src/components/button/button.svelte";
  import DBIcon from "../../../output/svelte/src/components/icon/icon.svelte";
</script>

<main>
  <h1>Svelte</h1>
  <div style="display: flex; gap: 4px; align-items: center">
    <DBButton variant="primary">Test</DBButton>
    <DBButton text="Test" icon="account" />
    <DBIcon icon="account" />
  </div>
</main>
